
CREATE TABLE COMM001
(

	CODE	VARCHAR(4)		NOT NULL,
	CATEGORY VARCHAR(20) 	NOT NULL,	
	CONTENT	VARCHAR(20)	NOT NULL,
	CONSTRAINT COMM_PK PRIMARY KEY (CODE));



CREATE TABLE USERS 
(       
    USER_NO     INTEGER(10)      NOT NULL, -- 회원고유번호
    USER_ID     VARCHAR(50)    NOT NULL, -- 아이디
    USER_PW     VARCHAR(6)     NOT NULL, -- 비밀번호
    USER_NAME   VARCHAR(20)    NOT NULL, -- 이름
         SEX CHAR(1) NOT NULL,
    BIRTH       VARCHAR(10)    NOT NULL, -- 생년월일
    EMAIL       VARCHAR(20)    NOT NULL, -- 이메일
    PHONE_NO    VARCHAR(20)    NOT NULL, -- 핸드폰번호
    USER_ZCODE  VARCHAR(20)    NOT NULL, -- 우편번호?
    ADDR1       VARCHAR(50)    NOT NULL, -- 주소상세1 API 확인 필요
    ADDR2       VARCHAR(50)    NOT NULL, -- 주소상세2
    CREATEDATE  DATE            NOT NULL, -- 가입날짜
    UPDATEDATE  DATE            NOT NULL,         -- 업데이트 날짜? 
    LASTLOGIN   DATE            NOT NULL, -- 마지막 접속 날짜
    USER_USE    CHAR(1)         NOT NULL, -- 아이디 사용 여부
    CART        VARCHAR(50)    ,         -- 장바구니
    CODE        VARCHAR(4)     NOT NULL, -- 권한
    
     CONSTRAINT USER_PK PRIMARY KEY (USER_NO,USER_ID),
     CONSTRAINT ROLE_CODE FOREIGN KEY(CODE) REFERENCES COMM001(CODE)
); 











	
COMMENT ON COLUMN USERS.USER_NO 	IS '회원고유번호';
COMMENT ON COLUMN USERS.USER_ID 	IS '아이디';
COMMENT ON COLUMN USERS.USER_PW 	IS '비밀번호';
COMMENT ON COLUMN USERS.SEX 		IS '성별';
COMMENT ON COLUMN USERS.BIRTH 		IS '생년월일';
COMMENT ON COLUMN USERS.EMAIL 		IS '이메일';
COMMENT ON COLUMN USERS.PHONE_NO 	IS '핸드폰번호';
COMMENT ON COLUMN USERS.USER_ZCODE 	IS '';
COMMENT ON COLUMN USERS.ADDR1 		IS '';
COMMENT ON COLUMN USERS.ADDR2 		IS '';
COMMENT ON COLUMN USERS.CREATEDATE 	IS '가입날짜';
COMMENT ON COLUMN USERS.UPDATEDATE 	IS '업데이트날짜';
COMMENT ON COLUMN USERS.LASTLOGIN 	IS '마지막접속날짜';
COMMENT ON COLUMN USERS.USER_USE 	IS '아이디사용여부';
COMMENT ON COLUMN USERS.CART 		IS '장바구니';
COMMENT ON COLUMN USERS.CODE 		IS '권한';
	
  
CREATE TABLE PRODUCT
(
    PRODUCT_NO        VARCHAR2(20)      NOT NULL, 
    PRODUCT_ID        VARCHAR2(20)      NULL, 
    PRODUCT_NAME      VARCHAR2(20)      NULL, 
    PUBLISHER         VARCHAR2(20)      NULL, 
    PRODUCT_STATUS    VARCHAR2(5)       NULL, 
    PRODUCT_PRICE     NUMBER            NULL, 
    CATEGORYS          VARCHAR2(4)       NULL, 
    QUANTITY          NUMBER            NULL, 
    DETAIL            VARCHAR2(2000)    NULL, 
    IMAGE             VARCHAR2(2000)    NULL, 
    PRODUCT_RATING    NUMBER            NULL, 
    SALES_QUANTITY    NUMBER            NULL, 
    AUTHOR            VARCHAR2(20)      NULL, 
    CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_NO)
);

COMMENT ON TABLE PRODUCT IS '상품';
COMMENT ON COLUMN PRODUCT.PRODUCT_NO IS '상품번호';
COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS '상품아이디';
COMMENT ON COLUMN PRODUCT.PRODUCT_NAME IS '상품이름';
COMMENT ON COLUMN PRODUCT.PUBLISHER IS '출판사';
COMMENT ON COLUMN PRODUCT.PRODUCT_STATUS IS '상품상태';
COMMENT ON COLUMN PRODUCT.PRODUCT_PRICE IS '상품가격';
COMMENT ON COLUMN PRODUCT.CATEGORYS IS '카테고리';
COMMENT ON COLUMN PRODUCT.QUANTITY IS '수량';
COMMENT ON COLUMN PRODUCT.DETAIL IS '상품설명';
COMMENT ON COLUMN PRODUCT.IMAGE IS '상품이미지';
COMMENT ON COLUMN PRODUCT.PRODUCT_RATING IS '상품평점';
COMMENT ON COLUMN PRODUCT.SALES_QUANTITY IS '판매수량';
COMMENT ON COLUMN PRODUCT.AUTHOR IS '저자명';

COMMIT;