/*[sqlpus 프롬프트에서 아래와 같이 작성하여 설정을 변경해 준다.]*/
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

/* CREATE USER */
CREATE USER TP IDENTIFIED BY 1234;

/* 권한부여 */
GRANT CREATE SESSION, CONNECT RESOURCE, DBA TO TP;

/* 해당 테이블 스페이스의 용량 제한없이 사용 가능 */
--ALTER USER TP DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;